# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_load_escuelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegiatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
