# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hijos_differentes_papas', models.IntegerField(default=0)),
                ('explicacion_solvencia', models.TextField()),
                ('estado_civil', models.TextField(choices=[('soltero', 'Soltero'), ('viudo', 'Viudo'), ('union libre', 'Unión Libre'), ('casado civil', 'Casado-Civil'), ('casado iglesia', 'Casado-Iglesia'), ('vuelto a casar', 'Divorciado Vuelto a Casar')])),
                ('localidad', models.TextField(choices=[('Poblado Jurica', 'Poblado Juríca'), ('Nabo', 'Nabo'), ('Salitre', 'Salitre'), ('La Campana', 'La Campana'), ('otro', 'Otro')])),
            ],
        ),
    ]
