# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 02:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.Familia')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('telefono', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999" Up to 15 numbers allowed', regex='^\\+?1?\\d{9,15}$')])),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('nivel_estudios', models.TextField(choices=[('ninguno', 'Ninguno'), ('1º grado', 'Primero de Primaria'), ('2º grado', 'Segundo de Primaria'), ('3º grado', 'Tercero de Primaria'), ('4º grado', 'Cuarto de Primaria'), ('5º grado', 'Quinto de Primaria'), ('6º grado', 'Sexto de Primaria'), ('7º grado', 'Primero de Secundaria'), ('8º grado', 'Segundo de Secundaria'), ('9º grado', 'Tercero de Secundaria'), ('10º grado', 'Primero de Pecundaria'), ('11º grado', 'Segundo de Preparatoria'), ('12º grado', 'Tercero de Preparatoria'), ('universidad', 'Universidad'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')])),
                ('fecha_de_nacimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.Familia')),
            ],
        ),
    ]
