# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='numero_hijos_differentes_papas',
            new_name='numero_hijos_diferentes_papas',
        ),
    ]
