# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0002_comentario_integrante'),
        ('familias', '0002_auto_20170223_0513'),
    ]

    operations = [
    ]
