# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 01:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0004_alumno_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999" Up to 15 numbers allowed', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
