# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0005_auto_20170225_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='explicacion_solvencia',
            field=models.TextField(blank=True),
        ),
    ]
