# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0006_auto_20170228_0225'),
        ('familias', '0005_auto_20170224_0226'),
    ]

    operations = [
    ]
