# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0008_auto_20170303_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='estado_civil',
            field=models.TextField(choices=[('soltero', 'Soltero'), ('viudo', 'Viudo'), ('union_libre', 'Unión Libre'), ('casado_civil', 'Casado-Civil'), ('casado_iglesia', 'Casado-Iglesia'), ('vuelto_a_casar', 'Divorciado Vuelto a Casar')], default='soltero'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='localidad',
            field=models.TextField(choices=[('poblado_jurica', 'Poblado Juríca'), ('nabo', 'Nabo'), ('salitre', 'Salitre'), ('la_campana', 'La Campana'), ('otro', 'Otro')], default='poblado_jurica'),
        ),
    ]
