# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0009_auto_20170314_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='integrante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_integrante', to='familias.Integrante'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_familia', to='familias.Familia'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrante_familia', to='familias.Familia'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='integrante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_integrante', to='familias.Integrante'),
        ),
    ]
