# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 18:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('familias', '0011_auto_20170321_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.Escuela'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='numero_sae',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrante',
            name='nivel_estudios',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('1_grado', 'Primero de Primaria'), ('2_grado', 'Segundo de Primaria'), ('3_grado', 'Tercero de Primaria'), ('4_grado', 'Cuarto de Primaria'), ('5_grado', 'Quinto de Primaria'), ('6_grado', 'Sexto de Primaria'), ('7_grado', 'Primero de Secundaria'), ('8_grado', 'Segundo de Secundaria'), ('9_grado', 'Tercero de Secundaria'), ('10_grado', 'Primero de Pecundaria'), ('11_grado', 'Segundo de Preparatoria'), ('12_grado', 'Tercero de Preparatoria'), ('universidad', 'Universidad'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], default='6_grado', max_length=200),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999" Up to 15 numbers allowed', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
