# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0012_auto_20170323_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='numero_sae',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='relacion',
            field=models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('tutor', 'Tutor')], max_length=75),
        ),
    ]
