# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0013_auto_20170323_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='numero_sae',
            field=models.CharField(default='000', max_length=30),
        ),
    ]
