# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0014_auto_20170328_1401'),
        ('familias', '0010_auto_20170319_1850'),
    ]

    operations = [
    ]
