# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 17:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0015_merge_20170328_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_alumno', to='administracion.Escuela'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.Familia'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='El número de telefono tiene que tener el siguiente formato: "+999999999" El número tiene que tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
