# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0017_auto_20170328_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Escuela'),
        ),
    ]
