# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0020_auto_20170329_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='numero_sae',
            field=models.CharField(max_length=30),
        ),
    ]
