# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0021_auto_20170329_0448'),
        ('familias', '0018_auto_20170328_2357'),
    ]

    operations = [
    ]
