# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0023_auto_20170331_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='nombre_familiar',
            field=models.CharField(default='Lopez', max_length=300),
            preserve_default=False,
        ),
    ]
