# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0024_familia_nombre_familiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='historial_terapia',
            field=models.TextField(blank=True, verbose_name='¿ASISTE O ASISTÍO A TERAPIA POR ALGUNA SITUACÓN DE AA, PSICOLOGIA, PSIQUIATRA, ETC.?'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='sacramentos_faltantes',
            field=models.TextField(blank=True, verbose_name='ACRAMENTOS QUE LE FALTEN… BAUTIZO, COMUNION, CONFIRMACIÓN, MATRIMONIO IGLESIA'),
        ),
    ]
