# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0025_auto_20170425_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='rol',
            field=models.CharField(default='ninguno', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrante',
            name='sacramentos_faltantes',
            field=models.TextField(blank=True, verbose_name='SACRAMENTOS QUE LE FALTEN… BAUTIZO, COMUNION, CONFIRMACIÓN, MATRIMONIO IGLESIA'),
        ),
    ]
