# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0026_auto_20170425_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='integrante',
            name='rol',
            field=models.CharField(max_length=150, verbose_name='Relación en la familia'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='oficio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familias.Oficio'),
        ),
    ]
