# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-29 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0028_load_oficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='historial_terapia',
            field=models.TextField(blank=True, verbose_name='¿Asiste o asistió a terapia por alguna situación de AA, psicología, psiquiatría, etc.?'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familias.Oficio'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='sacramentos_faltantes',
            field=models.TextField(blank=True, verbose_name='Sacramentos que le falten… bautizo, comunion, confirmación, matrimnio iglesia'),
        ),
    ]
