# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-29 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0030_familia_offline_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='offline_id',
        ),
        migrations.AddField(
            model_name='integrante',
            name='offline_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
