# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-29 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0029_auto_20170429_0121'),
        ('familias', '0031_auto_20170429_2136'),
    ]

    operations = [
    ]
