# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0034_integrante_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='escuela',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
