# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-20 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0033_auto_20170429_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='escuela',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
