# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0035_auto_20170621_2211'),
        ('familias', '0034_add_oficio_estudiante'),
    ]

    operations = [
    ]
