# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0037_auto_20170622_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='integrante',
            name='sacramentos',
            field=models.ManyToManyField(to='familias.Sacramento'),
        ),
    ]
