# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-23 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0037_auto_20170622_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='banio',
            field=models.CharField(blank=True, choices=[('Regadera', 'Regadera'), ('Jicarasos', 'Jicarasos'), ('Otro', 'Otro')], max_length=100, verbose_name='Tipo de instalación de baño'),
        ),
        migrations.AddField(
            model_name='familia',
            name='sanitarios',
            field=models.CharField(blank=True, choices=[('Escusado', 'Escusado'), ('Letrina', 'Letrina'), ('Otro', 'Otro')], max_length=100, verbose_name='Tipo de instalación sanitaria'),
        ),
    ]
