# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-02 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0039_load_sacramentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='sacramentos',
            field=models.ManyToManyField(blank=True, to='familias.Sacramento'),
        ),
    ]
