# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0040_auto_20170702_0710'),
        ('familias', '0039_alumno_ciclo_escolar'),
    ]

    operations = [
    ]
