# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0040_add_ama_de_casa_oficio'),
        ('familias', '0040_auto_20170702_0710'),
    ]

    operations = [
    ]
