# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0007_merge_20170228_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=10, max_digits=12)),
                ('fecha_de_asignacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.Alumno')),
            ],
        ),
    ]
