# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
