# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0006_auto_20170228_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.TextField(choices=[('no comprobable', 'No comprobable'), ('comprobable', 'Comprobable')])),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.TextField()),
                ('factor', models.DecimalField(decimal_places=10, max_digits=12)),
                ('multiplica', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField()),
                ('es_ingreso', models.BooleanField()),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.Familia')),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Periodo')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='transaccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Transaccion'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familias.Tutor'),
        ),
    ]
