# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_auto_20170224_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='multiplicador',
            new_name='factor',
        ),
        migrations.AddField(
            model_name='periodo',
            name='multiplica',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
