# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_auto_20170224_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='tipo',
            field=models.CharField(choices=[('no comprobable', 'No comprobable'), ('comprobable', 'Comprobable')], max_length=100),
        ),
    ]
