# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_auto_20170405_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='familias.Familia'),
        ),
    ]
