# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_auto_20170406_2141'),
        ('indicadores', '0005_auto_20170407_1338'),
    ]

    operations = [
    ]
