# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0006_merge_20170407_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_ingresos', to='familias.Tutor'),
        ),
    ]
