# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0007_auto_20170417_0040'),
        ('indicadores', '0007_auto_20170408_1959'),
    ]

    operations = [
    ]
