# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0009_load_periodicidades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oficio',
        ),
    ]
