# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0002_retroalimentacion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroalimentacion',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentacion_estudio', to='estudios_socioeconomicos.Estudio'),
        ),
    ]
