# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('video', models.URLField()),
                ('seccion', models.CharField(choices=[('general', 'General'), ('administracion', 'Administración'), ('captura', 'Captura'), ('direccion', 'Dirección'), ('servicios escolares', 'Servicios Esolares')], max_length=80)),
            ],
        ),
    ]
