# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0002_auto_20170225_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='opcion',
            new_name='elecciones',
        ),
    ]
