# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0004_auto_20170227_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='relacionado_a_integrante',
        ),
    ]
