# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0005_auto_20170228_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='elecciones',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='eleccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudios_socioeconomicos.OpcionRespuesta'),
        ),
    ]
