# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0006_auto_20170308_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='status',
            field=models.TextField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('borrador', 'Borrador'), ('revision', 'Revisión'), ('eliminado', 'Eliminado')], default='borrador'),
        ),
    ]
