# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-18 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0007_auto_20170314_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_pregunta', to='estudios_socioeconomicos.Pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='subseccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='estudios_socioeconomicos.Subseccion'),
        ),
        migrations.AlterField(
            model_name='subseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsecciones', to='estudios_socioeconomicos.Seccion'),
        ),
    ]
