# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0008_auto_20170318_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_estudio', to='estudios_socioeconomicos.Estudio'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta', to='estudios_socioeconomicos.Pregunta'),
        ),
    ]
