# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0009_remove_estudio_numero_sae'),
        ('estudios_socioeconomicos', '0009_auto_20170319_1850'),
    ]

    operations = [
    ]
