# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0010_merge_20170329_0610'),
        ('estudios_socioeconomicos', '0010_merge_20170328_1443'),
    ]

    operations = [
    ]
