# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0011_merge_20170403_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudios_socioeconomicos.Estudio')),
            ],
        ),
    ]
