# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0012_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='status',
            field=models.TextField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('borrador', 'Borrador'), ('revision', 'Revisión'), ('eliminado_capturista', 'Eliminado'), ('eliminado_administrador', 'Eliminado')], default='borrador'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='file_name',
            field=models.CharField(max_length=300),
        ),
    ]
