# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0013_auto_20170417_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
