# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-09 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0014_auto_20170501_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='offline_id',
            field=models.TextField(blank=True),
        ),
    ]
