# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios_socioeconomicos', '0014_auto_20170501_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='file_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
